# Generated by Django 6.0.2 on 2026-04-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(help_text='Donor or grant name', max_length=255)),
                ('fund_type', models.CharField(choices=[('donation', 'Donation'), ('grant', 'Grant'), ('other', 'Other')], default='donation', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('post_reach', models.PositiveIntegerField(blank=True, null=True)),
                ('engagement', models.PositiveIntegerField(blank=True, help_text='Total likes, shares, and comments', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('student_count', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attendee_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
